version: '3.1'
services:

  blackhole:
    build:
      context: .
    environment:
      LOG_LEVEL: INFO
      UVICORN_LOG_LEVEL: info
    networks:
      blackhole:
        aliases:
          - blackhole
    ports:
      - "4200:4200"
    volumes:
      - .:/code

networks:
  blackhole:
    name: blackhole
